version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: nextcloud:fpm
    container_name: nextcloud-app
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: userpass
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: adminpass
    volumes:
      - nextcloud_data:/var/www/html
    expose:
      - "80"
    depends_on:
      - db

  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: always
    environment:
      # IMPORTANT: this must match your Nextcloud domain
      domain=upcube\\.ai
      username=admin
      password=collaborapass
    cap_add:
      - MKNOD
    expose:
      - "9980"
    depends_on:
      - app

volumes:
  db_data:
  nextcloud_data:



