version: '3.9'

services:
  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - db_maps:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=maps-root-pass
      - MYSQL_PASSWORD=maps-pass
      - MYSQL_DATABASE=nextcloud_maps
      - MYSQL_USER=nextcloud_maps

  app:
    image: nextcloud:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8096:80"   # expose maps instance on port 8096
    volumes:
      - nextcloud_maps:/var/www/html
    environment:
      - MYSQL_PASSWORD=maps-pass
      - MYSQL_DATABASE=nextcloud_maps
      - MYSQL_USER=nextcloud_maps
      - MYSQL_HOST=db

volumes:
  db_maps:
  nextcloud_maps:








